### ISSUE TITLE
Have pipx work independently of pyenv

### ISSUE THREAD

**Issue by aiguofer** [pipxproject/pipx#17]
I use pyenv to manage my python environments, but I like the ability to install executables in a sandbox using something like pipx.

I installed pipx using `curl -sL https://raw.githubusercontent.com/cs01/pipx/master/get-pipx.py | PYENV_VERSION=system python3`

However, at run time it seems to pick up some environment setup from pyenv.  This causes some issues, like not correctly adding pip to the venv.

There's a couple of workarounds: `PYENV_VERSION=system pipx install <pkg>` or `pipx install --python /usr/bin/python3 <pkg>`.

However, it'd be nice is pipx worked independent of the pyenv setup and just used the environment it was used to install itself (this is how pipsi seems to work currently).

Another issue with pyenv is that if you already have an executable installed in any of your pyenv managed environments, pyenv creates an executable shim in `~/.pyenv/shims/`. When pipx sees that this already exists, it doesn't create the symlink in `~/.local/bin` (because `~/.pyenv/shims/` is in `$PATH`)

**Comment by cs01** [comment]
> However, it'd be nice is pipx worked independent of the pyenv setup and just used the environment it was used to install itself (this is how pipsi seems to work currently).

I just pushed an update to do this. pipx associates new installations with the pipx virtualenv's python binary. This should fix the first problem. To get the update, run `pipx update pipx`.

> Another issue with pyenv is that if you already have an executable installed in any of your pyenv managed environments, pyenv creates an executable shim in ~/.pyenv/shims/. When pipx sees that this already exists, it doesn't create the symlink in ~/.local/bin (because ~/.pyenv/shims/ is in $PATH)

For this it seems like a valid course of action to not create the symlink when something is on your path.  The user should either use what's installed or uninstall it before continuing. What do you think? I don't use pyenv so maybe that isn't true with pyenv? 

We could add an `--overwrite` or `--force` flag if it really makes senset. How does pipsi handle this?

**Comment by aiguofer** [comment]
> I just pushed an update to do this. pipx associates new installations with the pipx virtualenv's python binary. This should fix the first problem. To get the update, run pipx update pipx.

Hey, I tried reinstalling pipx with the latest but still get the same error about the env not finding pip:

```
pipx --version
0.0.0.11
```
Not sure if it actually took up the latest version?

> For this it seems like a valid course of action to not create the symlink when something is on your path. The user should either use what's installed or uninstall it before continuing. What do you think? I don't use pyenv so maybe that isn't true with pyenv?
> 
> We could add an --overwrite or --force flag if it really makes senset. How does pipsi handle this?

Well, I can see legitimate situations where a package installed in your pyenv environment might require another package (for example flake8) that includes an executable. In that situation, I'd prefer to use the pipx installed version when using from commandline, while still having the other version installed in that environment to fulfill the dependency. 

I could also see situations where there might be a globally installed package (through an RPM, DEB, or other package format) that is an old version and you'd prefer to use the latest version installed through pipx (which would only be installed for the user).

In either case, I think it'd be nice if it made the symlink regardless and leave it up to the user to ensure their `$PATH` is set up how they want it (I believe this is what pipsi does). Where it would get interesting is what to do when there is already a binary (or symlink) with the same name in `~/.local/bin`.

I did realize that in my env, `~/.pyenv/shims` takes precedence over `~/.local/bin`, so there would probably need to be a note to remind people to set up their path such that `~/.local/bin` takes precedence.

**Comment by cs01** [comment]
Just pushed two changes

* write symlink even if binary is on PATH. (symlink is still not written if a different one exists)
* fixed the association of python version to the one used to install pipx. I tested that it works on my machine

Let me know what you think.

**Comment by aiguofer** [comment]
Awesome, haha I was actually just digging into the code and was about to create a pull request when I noticed you fixed it already :)

Yeah both are great! A note in the README about setting the $PATH so that `~/.local/bin` is first would be helpful for others.

Thanks for all your work!

**Comment by cs01** [comment]
>Thanks for all your work!

You're welcome! I am glad you're liking it and appreciate your input. 

> A note in the README about setting the $PATH so that ~/.local/bin is first would be helpful for others.

I am not sure I want to say exactly what the fix it in the README. Maybe for pyenv users that's the solution, maybe for others it's to erase one of the binaries?

**Comment by neersighted** [comment]
I think a gentle reminder about correctly adding `$PIPX_BIN_DIR` to the PATH is all that is needed. Most users should probably understand how to manage their PATH, and 'hard' rules aren't very helpful in my opinion, as configurations vary widely.

**Comment by cs01** [comment]
`PIPX_BIN_DIR` already is on the path. The issue is what to tell the user to do to handle multiple binaries with the same name on the path.

**Comment by neersighted** [comment]
Ah, I see I misunderstood the issue. In that case a reminder that pipx needs to come first to override system-installed (or, pyenv shim) binaries makes sense.

**Comment by aiguofer** [comment]
Yeah, I agree with neersighted. I think something along the lines of:

```
pipx installs executables by creating symlinks in $PIPX_BIN_DIR (which defaults to ~/.local/bin). If you want these to take precedence, you will need to make sure your $PATH is set-up correctly to have $PIPX_BIN_DIR at the top. If an executable or symlink already exists in $PIPX_BIN_DIR when you install the package through pipx, the existing file/symlink will not be overriden so you need to remove it first.
```

**Comment by cs01** [comment]
Is this still an issue or can it be closed?

**Comment by aiguofer** [comment]
Hey, yeah I believe this can be closed. I'm not sure if there's something in the README or docs yet addressing this, but the issue itself is solved.
